package com.gt.microservicios.app.envios.models.entity;
// Generated 13/10/2021 09:14:55 PM by Hibernate Tools 4.3.1

import com.gt.microservicios.app.envios.models.entity.Envio;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dimensiones generated by hbm2java
 */
@Entity
@Table(name = "dimensiones",
        catalog = "analisissistemas2"
)
public class Dimensiones implements java.io.Serializable {

    private long idDimensiones;
    private String descripcion;

    public Dimensiones() {
    }

    public Dimensiones(long idDimensiones) {
        this.idDimensiones = idDimensiones;
    }

    public Dimensiones(long idDimensiones, String descripcion, Set<Envio> envios) {
        this.idDimensiones = idDimensiones;
        this.descripcion = descripcion;
    }

    @Id
    @Column(name = "id_dimensiones", unique = true, nullable = false)
    public long getIdDimensiones() {
        return this.idDimensiones;
    }

    public void setIdDimensiones(long idDimensiones) {
        this.idDimensiones = idDimensiones;
    }

    @Column(name = "descripcion", length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
