package com.gt.microservicios.app.envios.models.entity;
// Generated 13/10/2021 09:14:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Envio generated by hbm2java
 */
@Entity
@Table(name = "envios",
        catalog = "analisissistemas2"
)
public class Envio implements java.io.Serializable {

    private Long idenvio;
    private String estado;
    private Long tipo_dimension;
    private Long idPedido;
    private Long tipo_peso;
    private Long alto;
    private String direccion;
    private Date fechaEntrega;
    private Long fondo;
    private Long largo;
    private String metodoEnvio;
    private String nota;
    private Long numeroSeguimiento;
    private byte[] pdf;
    private Long peso;

    public Envio() {
    }

    public Envio(Long tipo_dimension, String estado, Long idPedido, Long tipo_peso, Long alto, String direccion, Date fechaEntrega, Long fondo, Long largo, String metodoEnvio, String nota, Long numeroSeguimiento, byte[] pdf, Long peso) {
        this.tipo_dimension = tipo_dimension;
        this.estado = estado;
        this.idPedido = idPedido;
        this.tipo_peso = tipo_peso;
        this.alto = alto;
        this.direccion = direccion;
        this.fechaEntrega = fechaEntrega;
        this.fondo = fondo;
        this.largo = largo;
        this.metodoEnvio = metodoEnvio;
        this.nota = nota;
        this.numeroSeguimiento = numeroSeguimiento;
        this.pdf = pdf;
        this.peso = peso;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idenvio", unique = true, nullable = false)
    public Long getIdenvio() {
        return this.idenvio;
    }

    public void setIdenvio(Long idenvio) {
        this.idenvio = idenvio;
    }

    @Column(name = "estado", length = 20)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @JoinColumn(name = "id_pedido")
    public Long getIdPedido() {
        return this.idPedido;
    }

    @JoinColumn(name = "tipo_dimension")
    public Long getTipo_dimension() {
        return tipo_dimension;
    }

    public void setTipo_dimension(Long tipo_dimension) {
        this.tipo_dimension = tipo_dimension;
    }

    @JoinColumn(name = "tipo_peso")
    public Long getTipo_peso() {
        return tipo_peso;
    }

    public void setTipo_peso(Long tipo_peso) {
        this.tipo_peso = tipo_peso;
    }

    public void setIdPedido(Long idPedido) {
        this.idPedido = idPedido;
    }

    @Column(name = "alto")
    public Long getAlto() {
        return this.alto;
    }

    public void setAlto(Long alto) {
        this.alto = alto;
    }

    @Column(name = "direccion", length = 45)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_entrega", length = 10)
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }

    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

    @Column(name = "fondo")
    public Long getFondo() {
        return this.fondo;
    }

    public void setFondo(Long fondo) {
        this.fondo = fondo;
    }

    @Column(name = "largo")
    public Long getLargo() {
        return this.largo;
    }

    public void setLargo(Long largo) {
        this.largo = largo;
    }

    @Column(name = "metodo_envio", length = 45)
    public String getMetodoEnvio() {
        return this.metodoEnvio;
    }

    public void setMetodoEnvio(String metodoEnvio) {
        this.metodoEnvio = metodoEnvio;
    }

    @Column(name = "nota", length = 150)
    public String getNota() {
        return this.nota;
    }

    public void setNota(String nota) {
        this.nota = nota;
    }

    @Column(name = "numero_seguimiento")
    public Long getNumeroSeguimiento() {
        return this.numeroSeguimiento;
    }

    public void setNumeroSeguimiento(Long numeroSeguimiento) {
        this.numeroSeguimiento = numeroSeguimiento;
    }

    @Column(name = "pdf")
    public byte[] getPdf() {
        return this.pdf;
    }

    public void setPdf(byte[] pdf) {
        this.pdf = pdf;
    }

    @Column(name = "peso")
    public Long getPeso() {
        return this.peso;
    }

    public void setPeso(Long peso) {
        this.peso = peso;
    }

}
