package com.gt.microservicios.app.envios.models.entity;
// Generated 13/10/2021 09:14:55 PM by Hibernate Tools 4.3.1

import com.gt.microservicios.app.envios.models.entity.Envio;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pesos generated by hbm2java
 */
@Entity
@Table(name = "pesos",
        catalog = "analisissistemas2"
)
public class Pesos implements java.io.Serializable {

    private long idpesos;
    private String descripcion;
//    private Set<Envio> envios = new HashSet<Envio>(0);

    public Pesos() {
    }

    public Pesos(long idpesos) {
        this.idpesos = idpesos;
    }

    public Pesos(long idpesos, String descripcion, Set<Envio> envios) {
        this.idpesos = idpesos;
        this.descripcion = descripcion;
//        this.envios = envios;
    }

    @Id

    @Column(name = "idpesos", unique = true, nullable = false)
    public long getIdpesos() {
        return this.idpesos;
    }

    public void setIdpesos(long idpesos) {
        this.idpesos = idpesos;
    }

    @Column(name = "descripcion", length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

//    @JsonIgnoreProperties(value = {"pesos"}, allowSetters = true)
//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pesos")
//    public Set<Envio> getEnvios() {
//        return this.envios;
//    }
//
//    public void setEnvios(Set<Envio> envios) {
//        this.envios = envios;
//    }

}
