/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gt.microservicios.app.pedidos.models.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BitacoraDetPedEnvio generated by hbm2java
 */
@Entity
@Table(name="bitacora_det_ped_envio"
    ,catalog="analisissistemas2"
)
public class BitacoraDetPedEnvio  implements java.io.Serializable {


     private Long id;
     private Long id_pedido;
     private Long id_producto;
     private Long id_envio;
     private Long cantidad_enviada;

    public BitacoraDetPedEnvio() {
    }

    public BitacoraDetPedEnvio(Long id_pedido, Long id_producto, Long id_envio, Long cantidad_enviada) {
       this.id_pedido = id_pedido;
       this.id_producto = id_producto;
       this.id_envio = id_envio;
       this.cantidad_enviada = cantidad_enviada;
    }

   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="id_pedido")
    public Long getId_pedido() {
        return this.id_pedido;
    }
    
    public void setId_pedido(Long id_pedido) {
        this.id_pedido = id_pedido;
    }

    
    @Column(name="id_producto")
    public Long getId_producto() {
        return this.id_producto;
    }
    
    public void setId_producto(Long id_producto) {
        this.id_producto = id_producto;
    }

    
    @Column(name="id_envio")
    public Long getId_envio() {
        return this.id_envio;
    }
    
    public void setId_envio(Long id_envio) {
        this.id_envio = id_envio;
    }

    
    @Column(name="cantidad_enviada")
    public Long getCantidad_enviada() {
        return this.cantidad_enviada;
    }
    
    public void setCantidad_enviada(Long cantidad_enviada) {
        this.cantidad_enviada = cantidad_enviada;
    }

}



