package com.gt.microservicios.app.pedidos.models.entity;
// Generated 13/10/2021 09:14:55 PM by Hibernate Tools 4.3.1


import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="analisissistemas2"
)
public class Cliente  implements java.io.Serializable {


     private Long idCliente;
     private String email;
     private String nombre;
     private String status;
     private String telefono;
//     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Cliente() {
    }

    public Cliente(String email, String nombre, String status, String telefono, Set<Pedido> pedidos) {
       this.email = email;
       this.nombre = nombre;
       this.status = status;
       this.telefono = telefono;
//       this.pedidos = pedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente", unique=true, nullable=false)
    public Long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

//    @JsonIgnoreProperties(value={"cliente"}, allowSetters = true)
//    @OneToMany(mappedBy = "cliente", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
//    public Set<Pedido> getPedidos() {
//        return this.pedidos;
//    }
//    
//    public void setPedidos(Set<Pedido> pedidos) {
//        this.pedidos = pedidos;
//    }




}


