package com.gt.microservicios.app.pedidos.models.entity;
// Generated 13/10/2021 09:14:55 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePedidos generated by hbm2java
 */
@Entity
@Table(name="detalle_pedidos"
    ,catalog="analisissistemas2"
)
public class DetallePedidos  implements java.io.Serializable {


     private DetallePedidosId id;
     private Pedido pedido;
//     private Producto producto;
     private Long cantidadEnviada;
     private Long cantidadPedida;

    public DetallePedidos() {
    }

	
    public DetallePedidos(DetallePedidosId id, Pedido pedido, Producto producto) {
        this.id = id;
        this.pedido = pedido;
//        this.producto = producto;
    }
    public DetallePedidos(DetallePedidosId id, Pedido pedido, Producto producto, Long cantidadEnviada, Long cantidadPedida) {
       this.id = id;
       this.pedido = pedido;
//       this.producto = producto;
       this.cantidadEnviada = cantidadEnviada;
       this.cantidadPedida = cantidadPedida;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPedido", column=@Column(name="id_pedido", nullable=false) ), 
        @AttributeOverride(name="idProducto", column=@Column(name="id_producto", nullable=false) ) } )
    public DetallePedidosId getId() {
        return this.id;
    }
    
    public void setId(DetallePedidosId id) {
        this.id = id;
    }
    
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedido", nullable=false, insertable=false, updatable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    
//    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
//    @ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="id_producto", nullable=false, insertable=false, updatable=false)
//    public Producto getProducto() {
//        return this.producto;
//    }
//    
//    public void setProducto(Producto producto) {
//        this.producto = producto;
//    }

    
    @Column(name="cantidad_enviada")
    public Long getCantidadEnviada() {
        return this.cantidadEnviada;
    }
    
    public void setCantidadEnviada(Long cantidadEnviada) {
        this.cantidadEnviada = cantidadEnviada;
    }

    
    @Column(name="cantidad_pedida")
    public Long getCantidadPedida() {
        return this.cantidadPedida;
    }
    
    public void setCantidadPedida(Long cantidadPedida) {
        this.cantidadPedida = cantidadPedida;
    } 

    @Override
    public String toString() {
        return "DetallePedidos{" + "id=" + id + ", pedido=" + pedido + ", cantidadEnviada=" + cantidadEnviada + ", cantidadPedida=" + cantidadPedida + '}';
    }
    
    
}


