package com.gt.microservicios.app.pedidos.models.entity;
// Generated 13/10/2021 09:14:55 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedidos",
        catalog = "analisissistemas2"
)
public class Pedido implements java.io.Serializable {

    private Long idpedido;
    private Long idCliente;
    private Date fechaPedido;
    private String statusPedido;
    private Set<DetallePedidos> detallePedidos = new HashSet<DetallePedidos>(0);

    public Pedido() {
    }

    public Pedido(Long idCliente, Date fechaPedido, String statusPedido, Set<DetallePedidos> detallePedidoses) {
        this.idCliente = idCliente;
        this.fechaPedido = fechaPedido;
        this.statusPedido = statusPedido;
//        this.envios = envios;
        this.detallePedidos = detallePedidoses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idpedido", unique = true, nullable = false)
    public Long getIdpedido() {
        return this.idpedido;
    }

    public void setIdpedido(Long idpedido) {
        this.idpedido = idpedido;
    }

    @JoinColumn(name = "id_idCliente")
    public Long getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_pedido", length = 10)
    public Date getFechaPedido() {
        return this.fechaPedido;
    }

    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }

    @Column(name = "status_pedido", length = 20)
    public String getStatusPedido() {
        return this.statusPedido;
    }

    public void setStatusPedido(String statusPedido) {
        this.statusPedido = statusPedido;
    }

    @JsonIgnoreProperties(value = {"pedido"}, allowSetters = true)
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
    public Set<DetallePedidos> getDetallePedidos() {
        return this.detallePedidos;
    }

    public void setDetallePedidos(Set<DetallePedidos> detallePedidoses) {
        this.detallePedidos = detallePedidoses;
    }

}
