package com.gt.microservicios.app.pedidos.models.entity;
// Generated 15/10/2021 08:45:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="productos"
    ,catalog="analisissistemas2"
)
public class Producto  implements java.io.Serializable {


     private Long idProducto;
     private String descripcionProducto;
     private Double precio;
     private Long cantidadStock;
//     private Set<DetallePedidos> detallePedidoses = new HashSet<DetallePedidos>(0);

    public Producto() {
    }

    public Producto(String descripcionProducto, Double precio, Long cantidadStock, Set<DetallePedidos> detallePedidoses) {
       this.descripcionProducto = descripcionProducto;
       this.precio = precio;
       this.cantidadStock = cantidadStock;
//       this.detallePedidoses = detallePedidoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_producto", unique=true, nullable=false)
    public Long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Long idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="descripcion_producto", length=60)
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }

    
    @Column(name="precio", precision=22, scale=0)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    
    @Column(name="cantidad_stock")
    public Long getCantidadStock() {
        return this.cantidadStock;
    }
    
    public void setCantidadStock(Long cantidadStock) {
        this.cantidadStock = cantidadStock;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="productos")
//    public Set<DetallePedidos> getDetallePedidoses() {
//        return this.detallePedidoses;
//    }
//    
//    public void setDetallePedidoses(Set<DetallePedidos> detallePedidoses) {
//        this.detallePedidoses = detallePedidoses;
//    }




}


